---
- hosts: linux
  tasks:
  - name: create mulitiple directory
    file: 
      path: "{{ item }}"
      state: directory
    with_items: 
     - '/home/ansible/var1'
     - '/home/root/var2'
     - '/home/ansible/var3'
