---
- hosts: linux
  vars: 
    games:
       baseball: 11player
       cricket: 2player
       badminton: 4Player
  tasks: 
   - name: print variable
     debug: 
        msg: "key is {{ item.key }} and value is {{ item.value}}"
     with_dict: "{{ games }}"
        
 



